# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBUz8-XnQzJHdoLU9gIdxEKF502FprJL

eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avNDgfekoAG0sRtadlD5V4XgrJPkXGYz
"""

import pandas as pd
import sys
file_path = sys.argv[1]
data = pd.read_csv(file_path)

# Insight 1: Basic statistics
Insight_1 = "Basic statistics:\n" + data.describe().to_string()
with open("eda-in-1.txt", "w") as file:
    file.write(Insight_1)

# Insight 2: Data types and missing values (equal data.info())
data_types = data.dtypes
missing_values = data.isna().sum()
Insight_2 = "Data Types:\n" + data_types.to_string() + "\n\n" + "Missing Values:\n" + missing_values.to_string()
with open("eda-in-2.txt", "w") as file:
    file.write(Insight_2)

# Insight 4: Sample data
Insight_3 = "Sample of data:\n" +data.head().to_string()
with open("eda-in-3.txt", "w") as file:
    file.write(Insight_3)

import subprocess
subprocess.run(["python3", "vis.py", "traffic.csv"])