# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzB_Eadi6XycQBJYGqUSo8oCEuz4FkOz

load.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jcg7VLuNrX3347Qklo1ykuBwfnBnUIrH
"""

import argparse
import subprocess
import pandas as pd

# Load the Titanic dataset
data = pd.read_csv('traffic.csv')

data.info()
data.head()
subprocess.run(['python3', 'dpre.py', 'traffic.csv'])