# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rz7Kmw_GmC-Div4nS79X1_LFtvDFXEpq

model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlyGJljazSDh70P58RTS55pjHua8W-Sr

K-Mean Algorithm
"""

import pandas as pd

from sklearn.cluster import KMeans
from sklearn.impute import SimpleImputer
import sys

file_path = sys.argv[1]
data = pd.read_csv(file_path)

# Select the relevant features for K-means clustering
selected_features = data[['CarCount', 'BikeCount', 'BusCount', 'TruckCount', 'Total']]

# Create an imputer
imputer = SimpleImputer(strategy='mean')

# Fit and transform the data
X_filled = imputer.fit_transform(selected_features)

# Perform K-means clustering with k=3
kmeans = KMeans(n_clusters=3, random_state=1)
clusters = kmeans.fit_predict(X_filled)

# Add the cluster labels to the DataFrame
data['cluster'] = clusters

# Count the number of records in each cluster
cluster_counts = data['cluster'].value_counts()

# Save the cluster counts to a text file
cluster_counts.to_csv('k.txt', header=['count'], index_label='cluster')

# Assuming df is your DataFrame
column_data_types = data.dtypes

# Print the data types of each column
print(column_data_types)